# Generated by Django 4.2.5 on 2023-09-30 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='can_get_notification',
        ),
        migrations.RemoveField(
            model_name='user',
            name='google_auth_credentials',
        ),
        migrations.RemoveField(
            model_name='user',
            name='oauth_username',
        ),
        migrations.RemoveField(
            model_name='user',
            name='pin',
        ),
        migrations.AddField(
            model_name='user',
            name='primary_picture',
            field=models.FileField(blank=True, null=True, upload_to='vault/'),
        ),
    ]
