# Generated by Django 4.2.5 on 2023-10-02 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chain', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coin',
            name='Coin_type',
            field=models.CharField(choices=[('STABLE_COIN', 'STABLE_COIN'), ('POPULAR_COIN', 'POPULAR_COIN'), ('OTHER', 'OTHER')], default='STABLE_COIN', max_length=15, verbose_name='Coin Type'),
        ),
    ]
